version: '3.4'

services:
  postgres:
    image: postgres
    volumes:
      - ../data/postgres:/var/lib/postgresql/data
    restart: unless-stopped
    environment:
      POSTGRES_DB: application
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    networks:
      - appnet
networks:
  appnet:
    name: app_network